# Generated by Django 3.0.8 on 2020-08-20 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_created_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('joindate', models.DateField(blank=True, null=True, verbose_name='joindate')),
                ('firstname', models.CharField(max_length=255, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=255, verbose_name='lastname')),
                ('phoneno', phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None, verbose_name='phoneno')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('role', models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('mr', 'mr')], max_length=5)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userpro_created_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('discount', models.IntegerField(default=0, verbose_name='discount')),
                ('priceWithDiscount', models.IntegerField(default=0, verbose_name='priceWithDiscount')),
                ('doseInMG', models.IntegerField(default=0, verbose_name='doseInMG')),
                ('mgfdate', models.DateField(verbose_name='mgfdate')),
                ('expiredate', models.DateField(verbose_name='expiredate')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('image', models.ImageField(upload_to='products/')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categoryid', to='mr_tracker.Category')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_created_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='order_id')),
                ('pay_status', models.BooleanField(default=False, verbose_name='pay_status')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_created_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PaymentDetails',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('Quantity', models.IntegerField(verbose_name='Quantity')),
                ('totalAmount', models.IntegerField(verbose_name='totalAmount')),
                ('totalDiscount', models.IntegerField(verbose_name='totalDiscount')),
                ('OrderDate', models.DateField(blank=True, null=True, verbose_name='OrderDate')),
                ('deliveryDate', models.DateField(blank=True, null=True, verbose_name='deliveryDate')),
                ('order_flag', models.BooleanField(default=False, verbose_name='order_flag')),
                ('MRid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='MRid', to='mr_tracker.UserProfile')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_created_user', to=settings.AUTH_USER_MODEL)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_order', to='mr_tracker.PaymentDetails')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productID', to='mr_tracker.Product')),
            ],
            options={
                'verbose_name_plural': 'OrderDetails',
            },
        ),
        migrations.CreateModel(
            name='LocationOfDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('fullname', models.CharField(max_length=255, verbose_name='fullname')),
                ('phoneno', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phoneno')),
                ('state', models.CharField(max_length=255, verbose_name='state')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('pincode', models.CharField(max_length=6, verbose_name='pincode')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_created_user', to=settings.AUTH_USER_MODEL)),
                ('mrid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrid', to='mr_tracker.UserProfile')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_order_id', to='mr_tracker.PaymentDetails')),
            ],
            options={
                'verbose_name_plural': 'LocationOfDoctor',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('firstname', models.CharField(max_length=255, verbose_name='firstname')),
                ('phoneNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phoneNo')),
                ('lastname', models.CharField(max_length=255, verbose_name='state')),
                ('degree', models.CharField(max_length=255, verbose_name='degree')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_created_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'active'], name='mr_tracker__user_id_6dec46_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'phoneno', 'active'], name='mr_tracker__user_id_92466b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'active'], name='mr_tracker__name_93a3be_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'price', 'active'], name='mr_tracker__name_1c348c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdetails',
            index=models.Index(fields=['order_id', 'active'], name='mr_tracker__order_i_0c1135_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdetails',
            index=models.Index(fields=['order_id', 'pay_status', 'active'], name='mr_tracker__order_i_07270b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetails',
            index=models.Index(fields=['MRid', 'active'], name='mr_tracker__MRid_id_6a1e47_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetails',
            index=models.Index(fields=['MRid', 'productID', 'active'], name='mr_tracker__MRid_id_d52b18_idx'),
        ),
        migrations.AddIndex(
            model_name='locationofdoctor',
            index=models.Index(fields=['fullname', 'active'], name='mr_tracker__fullnam_1b7fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='locationofdoctor',
            index=models.Index(fields=['fullname', 'phoneno', 'active'], name='mr_tracker__fullnam_4232f5_idx'),
        ),
        migrations.AddIndex(
            model_name='doctors',
            index=models.Index(fields=['firstname', 'active'], name='mr_tracker__firstna_a005aa_idx'),
        ),
        migrations.AddIndex(
            model_name='doctors',
            index=models.Index(fields=['firstname', 'phoneNo', 'active'], name='mr_tracker__firstna_8239e3_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title', 'active'], name='mr_tracker__title_220843_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['description', 'title', 'active'], name='mr_tracker__descrip_0e0862_idx'),
        ),
    ]
