# Generated by Django 3.0.8 on 2020-08-20 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mr_tracker', '0002_remove_locationofdoctor_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationofdoctor',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='location_order_id', to='mr_tracker.PaymentDetails'),
            preserve_default=False,
        ),
    ]
